import pygame

SCALE_SIZE = (120, 120)
from weapon import active_traps
from astar import find_path

class Janitor:
    def __init__(self, x, y, tile_size):
        self.x = x
        self.y = y
        self.tile_size = tile_size
        self.speed = 2.2
        self.image = pygame.image.load("assets/janitor.png").convert_alpha()
        self.state = "patrol"
        self.defeat = False
        self.stun_timer = 0
        self.slip_until = 0

        self.frame = 0
        self.anim_speed = 0.12

        # IDLE
        self.idle_front = pygame.transform.scale(
            pygame.image.load("assets/janitor.png").convert_alpha(),
            SCALE_SIZE
        )

        self.idle_back = pygame.transform.scale(
            pygame.image.load("assets/janitor_back.png").convert_alpha(),
            SCALE_SIZE
        )

        # SPRITE SHEETS
        self.left_sheet = pygame.image.load("assets/janitor_walk_left.png").convert_alpha()
        self.right_sheet = pygame.image.load("assets/janitor_walk_right.png").convert_alpha()
        self.front_sheet = pygame.image.load("assets/janitor_walk_front.png").convert_alpha()
        self.back_sheet = pygame.image.load("assets/janitor_walk_back.png").convert_alpha()

       
        self.walk_left = self.load_sheet(self.left_sheet, 2, 2)
        self.walk_right = self.load_sheet(self.right_sheet, 2, 2)

        # front/back = 2 sprites = 2x1
        self.walk_front = self.load_sheet(self.front_sheet, 2, 1)
        self.walk_back = self.load_sheet(self.back_sheet, 2, 1)

        self.image = self.idle_front
        self.direction = "front"
        self.current_frames = self.walk_front

        # Minimum distance to the target before the janitor stops moving
        self.stop_distance = 24

        # Patrol points
        self.patrol_points = [
            (1728, 1128),  # Gym hallway left
            (3120, 1128),  # Gym hallway right
            (3120, 1512),  # Janitor hallway
            (1728, 1512)   # Maintenance hallway
            ]
        
        self.current_patrol = 0

        # Last place where player was seen
        self.last_seen = None

        # Search timer
        self.search_timer = 0

        # Detect distance
        self.detect_distance = 450

        # Current path generated by A*
        self.path = []

        # Which point in the path the janitor is walking to
        self.path_index = 0

        # Recalculate path every 0.2 seconds
        self.path_timer = 0

        self.rect = pygame.Rect(0, 0, 40, 40)
        self.rect.midbottom = (self.x, self.y)

  
    def load_sheet(self, sheet, rows, cols):
        frames = []

        w = sheet.get_width() // cols
        h = sheet.get_height() // rows

        for row in range(rows):
            for col in range(cols):
                frame = sheet.subsurface((col*w, row*h, w, h)).copy()
                frame = pygame.transform.scale(frame, SCALE_SIZE)
                frames.append(frame)

        return frames


    def animate(self):
        self.frame += self.anim_speed
        if self.frame >= len(self.current_frames):
            self.frame = 0
        return self.current_frames[int(self.frame)]


    def set_frames(self, new_frames):
        if self.current_frames != new_frames:
            self.current_frames = new_frames
            self.frame = 0  
<<<<<<< HEAD
        
        # if defeats the janitor js stops moving
        if self.defeat:
            return 
         # stops the janitor for 10 seconds
        if self.state == "stunned":
            if pygame.time.get_ticks() - self.stun_timer > 10000: 
                self.state = "chasing"
            else:
                return
                
    def update(self, player_x, player_y, walls):
=======

    def calculate_path(self, target_x, target_y, blocked):

        now = pygame.time.get_ticks()

        # Only recalculate every 0.2 seconds
        if now - self.path_timer < 200:
            return
        
        start = (
            int(self.x // self.tile_size),
            int(self.y // self.tile_size)
        )
        
        goal = (
            int(target_x // self.tile_size),
            int(target_y // self.tile_size)
        )

        grid_path = find_path(start, goal, blocked)

        new_path = [
            (
                gx * self.tile_size + self.tile_size // 2,
                gy * self.tile_size + self.tile_size // 2
            )
            for (gx, gy) in grid_path
        ]

        if new_path != self.path:
            self.path = new_path

            if len(self.path) > 1:
                self.path_index = 1

            else:
                self.path_index = 0

        self.path_timer = now

    def get_next_path_target(self, fallback):
        while self.path and self.path_index < len(self.path):
            target = self.path[self.path_index]

            distance = (
                (target[0] - self.x) ** 2 +
                (target[1] - self.y) ** 2
            ) ** 0.5

            if distance < self.stop_distance:
                self.path_index += 1
                continue

            return target
        
        return fallback
    
    def can_see_player(self, player_x, player_y, active_walls):

        start = (self.x, self.y)
        end = (player_x, player_y)

        # Check several points along the line
        steps = 20

        for i in range(steps + 1):

            t = i / steps

            check_x = start[0] + (end[0] - start[0]) * t
            check_y = start[1] + (end[1] - start[1]) * t

            point = pygame.Rect(check_x - 2, check_y - 2, 4, 4)

            for wall in active_walls:
                if point.colliderect(wall):
                    return False
                
        return True

    def update(self, player_x, player_y, blocked, active_walls):
>>>>>>> 8746b76 (Update janitor AI and hotel scene)
        
        # if defeats the janitor js stops moving
        if self.defeat:
            return 
         # stops the janitor for 10 seconds
        if self.state == "stunned":
            if pygame.time.get_ticks() - self.stun_timer > 10000: 
                self.state = "search"
                self.last_seen = (player_x, player_y)
                self.search_timer = pygame.time.get_ticks()
            else:
                return
            
        # if janitor is slipping
        if self.state == "slipping":
            now = pygame.time.get_ticks()
            
            if now < self.slip_until:
               self.slip_angle = (self.slip_angle + 10) % 360
               self.image = pygame.transform.rotate(self.idle_front, self.slip_angle)
               self.x -= 2
               self.y -= 1 
               self.rect.center = (self.x, self.y)
            else:
               self.image = pygame.transform.rotate(self.idle_front, 90)
            if now > self.lay_until:
                self.state = "search"
                self.last_seen = (player_x, player_y)
                self.search_timer = pygame.time.get_ticks()
            return

        distance_x = player_x - self.x
        distance_y = player_y - self.y

        distance = (distance_x**2 + distance_y**2) ** 0.5

        # Player spotted
        if (
            distance < self.detect_distance
            and self.can_see_player(player_x, player_y, active_walls)
        ):
            self.state = "chasing"
            self.last_seen = (player_x, player_y)

        # Janitor AI behaviour
        # Patrol state: Janitor follows a fixed patrol routed around the hotel
        if self.state == "patrol":

            patrol_x, patrol_y = self.patrol_points[self.current_patrol]

            self.calculate_path(
                patrol_x,
                patrol_y,
                blocked
            )

            target = self.get_next_path_target(
                (patrol_x, patrol_y)
            )

        # Chase state: Follow the calculated A* path instead of walking directly to the player
        elif self.state == "chasing":

            self.calculate_path(
                player_x,
                player_y,
                blocked
            )

            target = self.get_next_path_target(
                (player_x, player_y)
            )

        # Search state: If the player escapes, the janitor moves to the last location where the player was seen
        elif self.state == "search":

            if self.last_seen is None:
                self.state = "patrol"
                return
            
            self.calculate_path(
                self.last_seen[0],
                self.last_seen[1],
                blocked
            )

            target = self.get_next_path_target(self.last_seen)                
        
        dx = target[0] - self.x
        dy = target[1] - self.y

        #print(target)
        #print(dx, dy)
        print(
            "Waypoint:",
            self.path_index,
            target,
            "Position:",
            (round(self.x), round(self.y))
        )

        # Calculate smooth movement towards the current target
        length = (dx * dx + dy * dy) ** 0.5

        print(
            "Distance:", round(length, 2),
            " Stop:", self.stop_distance,
            " Waypoint:", self.path_index
        )

        # Stop moving when close to the target
        if length < self.stop_distance:
            
            if self.path and self.path_index < len(self.path):
                
                if self.path_index < len(self.path) - 1:
                    self.path_index += 1

                    target = self.path[self.path_index]

                    dx = target[0] - self.x
                    dy = target[1] - self.y
                    length = (dx * dx + dy * dy) ** 0.5

                else:
                    self.path = []
                    self.path_index = 0

            if self.direction == "back":
                self.image = self.idle_back
            else:
                self.image = self.idle_front

            # Patrol: move to the next patrol point
            if self.state == "patrol":
                self.current_patrol += 1

                if self.current_patrol >= len(self.patrol_points):
                    self.current_patrol = 0

                # Clear any old chase path
                self.path = []
                self.path_index = 0
                self.path_timer = 0

            # Search: finished searching
            elif self.state == "search":

                if pygame.time.get_ticks() - self.search_timer > 3000:
                    self.state = "patrol"

                    self.path = []
                    self.path_index = 0
                    self.path_timer = 0

            return
            

        # Decide animation
        if abs(dx) > abs(dy):

            if dx > 0:
                self.direction = "right"
                self.set_frames(self.walk_right)
            else:
                self.direction = "left"
                self.set_frames(self.walk_left)

        else:

            if dy > 0:
                self.direction = "front"
                self.set_frames(self.walk_front)
            else:
                self.direction = "back"
                self.set_frames(self.walk_back)

        # Normalized movement
        move_x = 0
        move_y = 0

        if length != 0:
            move_x = dx / length * self.speed
            move_y = dy / length * self.speed

        # Try X movement
        test_rect = self.rect.copy()
        test_rect.centerx += move_x

        hit_wall_x = False

        for wall in active_walls:
            if test_rect.colliderect(wall):
                hit_wall_x = True
                break

        if not hit_wall_x:
            self.x += move_x
            self.rect.centerx = self.x

        # Try Y movement
        test_rect = self.rect.copy()
        test_rect.centery += move_y

        hit_wall_y = False

        for wall in active_walls:
            if test_rect.colliderect(wall):
                hit_wall_y = True
                break

        if not hit_wall_y:
            self.y += move_y
            self.rect.centery = self.y

        # Sliding: If X blocked, try Y. If Y blocked, try X.
        if hit_wall_x or hit_wall_y:
            slide_rect = self.rect.copy()
            slide_rect.centerx += move_x

            if not any(slide_rect.colliderect(w) for w in active_walls):
                self.x += move_x
                self.rect.centerx = self.x

            slide_rect = self.rect.copy()

            slide_rect.centery += move_y

            if not any(slide_rect.colliderect(w) for w in active_walls):
                self.y += move_y
                self.rect.centery = self.y

        # Keep collision box synced
        self.rect.center = (self.x, self.y)

        self.image = self.animate()

        # Handle AI state changes

        # Chase: player escaped detection range
        if self.state == "chasing":
            distance = ((player_x - self.x) ** 2 + (player_y - self.y) ** 2) ** 0.5

            if distance > self.detect_distance:
                self.state = "search"
                self.last_seen = (player_x, player_y)
                self.search_timer = pygame.time.get_ticks()

       # check for trap collisions
        for trap in active_traps[:]:
            if self.state == "chasing" and self.rect.colliderect(trap["rect"]):
                self.weapon_effect("BananaPeel")
                active_traps.remove(trap)

    def draw(self, screen, camera_x=0, camera_y=0):

        rect = self.image.get_rect(
            midbottom=(
                self.x - camera_x,
                self.y - camera_y
            )
        )

        screen.blit(self.image, rect)

    def weapon_effect (self, effect):
        if effect== "BananaPeel":
            self.state = "slipping"
            self.slip_until = pygame.time.get_ticks() + 2000
            self.lay_until = pygame.time.get_ticks() + 40000
            self.slip_angle = 0

            # Trigger popup message
            self.popup_message = "The janitor is now gone for 40 seconds"
            self.popup_start_time = pygame.time.get_ticks()
            self.popup_duration = 3000  # show for 3 seconds

        elif effect == "CleaningSpray":
            self.state = "stunned" 
            self.stun_timer = pygame.time.get_ticks()

        elif effect == "BaseballBat":
            self.state = "defeated"
            self.defeat = True
