import pygame

SCALE_SIZE = (150, 150)
from weapon import active_traps
from astar import find_path

class Janitor:
    def __init__(self, x, y, tile_size):
        self.x = x
        self.y = y
        self.tile_size = tile_size
        self.speed = 1.5
        self.image = pygame.image.load("assets/janitor.png").convert_alpha()
        self.state = "patrol"
        self.defeat = False
        self.stun_timer = 0
        self.slip_until = 0

        self.frame = 0
        self.anim_speed = 0.12

        # IDLE
        self.idle_front = pygame.transform.scale(
            pygame.image.load("assets/janitor.png").convert_alpha(),
            SCALE_SIZE
        )

        self.idle_back = pygame.transform.scale(
            pygame.image.load("assets/janitor_back.png").convert_alpha(),
            SCALE_SIZE
        )

        # SPRITE SHEETS
        self.left_sheet = pygame.image.load("assets/janitor_walk_left.png").convert_alpha()
        self.right_sheet = pygame.image.load("assets/janitor_walk_right.png").convert_alpha()
        self.front_sheet = pygame.image.load("assets/janitor_walk_front.png").convert_alpha()
        self.back_sheet = pygame.image.load("assets/janitor_walk_back.png").convert_alpha()

       
        self.walk_left = self.load_sheet(self.left_sheet, 2, 2)
        self.walk_right = self.load_sheet(self.right_sheet, 2, 2)

        # front/back = 2 sprites = 2x1
        self.walk_front = self.load_sheet(self.front_sheet, 2, 1)
        self.walk_back = self.load_sheet(self.back_sheet, 2, 1)

        self.image = self.idle_front
        self.direction = "front"
        self.current_frames = self.walk_front

        # Minimum distance to the target before the janitor stops moving
        self.stop_distance = 20

        # Patrol points
        self.patrol_points = [
            (1700, 1148),  # change coordinates later
            (2208, 1056),
            (2208, 1800),
            (1632, 1800)
            ]
        
        self.current_patrol = 0

        # Last place where player was seen
        self.last_seen = None

        # Search timer
        self.search_timer = 0

        # Detect distance
        self.detect_distance = 450

        # Current path generated by A*
        self.path = []

        # Which point in the path the janitor is walking to
        self.path_index = 0

        # Recalculate path every 0.5 seconds
        self.path_timer = 0

        self.rect = pygame.Rect(0, 0, 40, 40)
        self.rect.midbottom = (self.x, self.y)

  
    def load_sheet(self, sheet, rows, cols):
        frames = []

        w = sheet.get_width() // cols
        h = sheet.get_height() // rows

        for row in range(rows):
            for col in range(cols):
                frame = sheet.subsurface((col*w, row*h, w, h)).copy()
                frame = pygame.transform.scale(frame, SCALE_SIZE)
                frames.append(frame)

        return frames


    def animate(self):
        self.frame += self.anim_speed
        if self.frame >= len(self.current_frames):
            self.frame = 0
        return self.current_frames[int(self.frame)]


    def set_frames(self, new_frames):
        if self.current_frames != new_frames:
            self.current_frames = new_frames
            self.frame = 0  

    def update(self, player_x, player_y, blocked, active_walls):
        
        # if defeats the janitor js stops moving
        if self.defeat:
            return 
         # stops the janitor for 10 seconds
        if self.state == "stunned":
            if pygame.time.get_ticks() - self.stun_timer > 10000: 
                self.state = "search"
                self.last_seen = (player_x, player_y)
                self.search_timer = pygame.time.get_ticks()
            else:
                return
            
        # if janitor is slipping
        if self.state == "slipping":
            now = pygame.time.get_ticks()
            
            if now < self.slip_until:
               self.slip_angle = (self.slip_angle + 10) % 360
               self.image = pygame.transform.rotate(self.idle_front, self.slip_angle)
               self.x -= 2
               self.y -= 1 
               self.rect.midbottom = (self.x, self.y)

            else:
               self.image = pygame.transform.rotate(self.idle_front, 90)
            if now > self.lay_until:
                self.state = "search"
                self.last_seen = (player_x, player_y)
                self.search_timer = pygame.time.get_ticks()
            return

        distance_x = player_x - self.x
        distance_y = player_y - self.y

        distance = (distance_x**2 + distance_y**2) ** 0.5

        # Player spotted
        if distance < self.detect_distance:
            self.state = "chasing"
            self.last_seen = (player_x, player_y)

        # Janitor AI behaviour
        # Patrol state: Janitor follows a fixed patrol routed around the hotel
        if self.state == "patrol":
            target = self.patrol_points[self.current_patrol]

        # Chase state: Follow the calculated A* path instead of walking directly to the player
        elif self.state == "chasing":
            now = pygame.time.get_ticks()

            # Recalculate the path every 0.5 seconds
            if now - self.path_timer > 500:

                # Convert positions into tile coordinates
                start = (int(self.x // self.tile_size), int(self.y // self.tile_size))
                goal = (int(player_x // self.tile_size), int(player_y // self.tile_size))

                # Use blocked tile set instead of rects
                grid_path = find_path(start, goal, blocked)   # blocked = tile coordinates

                print("Start:", start)
                print("Goal :", goal)
                print("Path length:", len(grid_path))

                # Convert back into pixel coordinates for movement
                new_path = [
                    (
                        gx * self.tile_size + self.tile_size // 2, 
                        gy * self.tile_size + self.tile_size // 2
                        ) 
                        for (gx, gy) in grid_path
                ]

                if new_path != self.path:
                    self.path = new_path

                    if len(self.path) > 1:
                        self.path_index = 1
                    else:
                        self.path_index = 0

                self.path_timer = now

            # Move toward the next point in the path
            if self.path and self.path_index < len(self.path):
                target = self.path[self.path_index]

                print("Current target:", target)
                print("Current position:", self.x, self.y)

            else:
                target = (player_x, player_y)

        # Search state: If the player escapes, the janitor moves to the last location where the player was seen
        elif self.state == "search":
            target = self.last_seen

        dx = target[0] - self.x
        dy = target[1] - self.y

        #print(target)
        #print(dx, dy)
        print(
            "Waypoint:",
            self.path_index,
            target,
            "Position:",
            (round(self.x), round(self.y))
        )

        # Calculate smooth movement towards the current target
        length = (dx * dx + dy * dy) ** 0.5

        print(
            "Distance:", round(length, 2),
            " Stop:", self.stop_distance,
            " Waypoint:", self.path_index
        )

        # Stop moving when close to the target
        if length < self.stop_distance:

            # Chase: reached one waypoint, continue to the next waypoint
            if self.state == "chasing":

                while self.path_index < len(self.path) - 1:
                    self.path_index += 1

                    target = self.path[self.path_index]

                    dx = target[0] - self.x
                    dy = target[1] - self.y

                    if (dx*dx + dy*dy)**0.5 > self.stop_distance:
                         break
                return

            if self.direction == "back":
                self.image = self.idle_back
            else:
                self.image = self.idle_front

            # Patrol: move to the next patrol point
            if self.state == "patrol":
                self.current_patrol += 1

                if self.current_patrol >= len(self.patrol_points):
                    self.current_patrol = 0

            # Search: finished searching
            elif self.state == "search":

                if pygame.time.get_ticks() - self.search_timer > 3000:
                    self.state = "patrol"

            return
            

        # movement + animation logic (FIXED DIAGONAL ISSUE)

        move_x = 0
        move_y = 0

        # Prioritize whichever axis has stronger movement
        if abs(dx) > abs(dy):   # horizontal movement dominates
            if dx > 0:
                self.direction = "right"
                self.set_frames(self.walk_right)
            else:
                self.direction = "left"
                self.set_frames(self.walk_left)
        else:                   # vertical movement dominates
            if dy > 0:
                self.direction = "front"
                self.set_frames(self.walk_front)
            else:
                self.direction = "back"
                self.set_frames(self.walk_back)

        move_x = 0
        move_y = 0

        if length !=0:
            move_x = dx / length * self.speed
            move_y = dy / length * self.speed

            print("move_x =", move_x)
            print("move_y =", move_y)

        # Horizontal collision
        janitor_rect = self.rect.copy()
        janitor_rect.x += move_x

        print("Horizontal rect:", janitor_rect)

        # Use active_walls (rects) for collision checks
        for wall in active_walls:
            if janitor_rect.inflate(-4, -4).colliderect(wall):
                print("Horizontal collision with wall:", wall)
                blocked_collision = True
                break
        else:
            blocked_collision = False

        print("Horizontal blocked:", blocked_collision)

        if not blocked_collision:
            self.x += move_x
            self.rect.midbottom = (self.x, self.y)
        else:
            print("HORIZONTAL COLLISION!")

        # Vertical collision
        janitor_rect = self.rect.copy()
        janitor_rect.y += move_y

        print("Vertical rect:", janitor_rect)

        for wall in active_walls:
            if janitor_rect.colliderect(wall):
                print("Vertical collision with wall:", wall)
                blocked_collision = True
                break
        else:
            blocked_collision = False

        print("Vertical blocked:", blocked_collision)

        if not blocked_collision:
            self.y += move_y
            self.rect.midbottom = (self.x, self.y)
        else:
            print("VERTICAL COLLISION!")

        # Update animation
        self.image = self.animate()

        # Handle AI state changes

        # Chase: player escaped detection range
        if self.state == "chasing":
            distance = ((player_x - self.x) ** 2 + (player_y - self.y) ** 2) ** 0.5

            if distance > self.detect_distance:
                self.state = "search"
                self.last_seen = (player_x, player_y)
                self.search_timer = pygame.time.get_ticks()

       # check for trap collisions
        for trap in active_traps[:]:
            if self.state == "chasing" and self.rect.colliderect(trap["rect"]):
                self.weapon_effect("BananaPeel")
                active_traps.remove(trap)

    def draw(self, screen, camera_x=0, camera_y=0):

        rect = self.image.get_rect(
            midbottom=(
                self.x - camera_x,
                self.y - camera_y
            )
        )

        screen.blit(self.image, rect)

    def weapon_effect (self, effect):
        if effect== "BananaPeel":
            self.state = "slipping"
            self.slip_until = pygame.time.get_ticks() + 2000
            self.lay_until = pygame.time.get_ticks() + 40000
            self.slip_angle = 0

            # Trigger popup message
            self.popup_message = "The janitor is now gone for 40 seconds"
            self.popup_start_time = pygame.time.get_ticks()
            self.popup_duration = 3000  # show for 3 seconds

        elif effect == "CleaningSpray":
            self.state = "stunned" 
            self.stun_timer = pygame.time.get_ticks()

        elif effect == "BaseballBat":
            self.state = "defeated"
            self.defeat = True
