import pygame

SCALE_SIZE = (140, 140)
from weapon import active_traps
from astar import find_path

class Receptionist:
    def __init__(self, x, y, tile_size):
        self.x = x
        self.y = y
        self.tile_size = tile_size
        self.speed = 1.5
        self.state = "patrol"
        self.defeat = False
        self.stun_timer = 0
        self.slip_until = 0 
        self.lay_until = 0
        self.slip_angle = 0
        self.original_speed = self.speed
        self.frame = 0
        self.anim_speed = 0.12

        # IDLE
        self.idle_front = pygame.transform.scale(
            pygame.image.load("assets/receptionist.png").convert_alpha(),
            SCALE_SIZE
        )

        self.idle_back = pygame.transform.scale(
            pygame.image.load("assets/receptionist_back.png").convert_alpha(),
            SCALE_SIZE
        )

        # SPRITE SHEETS
        self.left_sheet = pygame.image.load("assets/receptionist_walk_left.png").convert_alpha()
        self.right_sheet = pygame.image.load("assets/receptionist_walk_right.png").convert_alpha()
        self.front_sheet = pygame.image.load("assets/receptionist_walk_front.png").convert_alpha()
        self.back_sheet = pygame.image.load("assets/receptionist_walk_back.png").convert_alpha()

        # ✅ FIXED SIZES
        # left/right = 2x2 (4 frames total)
        self.walk_left = self.load_sheet(self.left_sheet, 2, 2)
        self.walk_right = self.load_sheet(self.right_sheet, 2, 2)

        # front/back = 2 sprites = 2x1
        self.walk_front = self.load_sheet(self.front_sheet, 2, 1)
        self.walk_back = self.load_sheet(self.back_sheet, 2, 1)

        self.image = self.idle_front
        self.direction = "front"
        self.current_frames = self.walk_front

        self.stop_distance = 40

        # Patrol points
        self.patrol_points = [    # change coordinates later
            (2783, 1864),
            (1200, 820),
            (1200, 500),
            (650, 500)
        ]

        self.current_patrol = 0

        # Last place where player was seen
        self.last_seen = None

        # Search timer
        self.search_timer = 0

        # Detect distance
        self.detect_distance = 450

        # Current path generated by A*
        self.path = []      

        # Which point in the path the receptionist is walking to
        self.path_index = 0

        # Recalculate path timer
        self.path_timer = 0

        # Used to detect when the janitor is stuck
        self.last_position = (self.x, self.y)
        self.stuck_timer = pygame.time.get_ticks()

        self.rect = pygame.Rect(0, 0, 40, 40)
        self.rect.midbottom = (self.x, self.y)
  
    def load_sheet(self, sheet, rows, cols):
        frames = []

        w = sheet.get_width() // cols
        h = sheet.get_height() // rows

        for row in range(rows):
            for col in range(cols):
                frame = sheet.subsurface((col*w, row*h, w, h)).copy()
                frame = pygame.transform.scale(frame, SCALE_SIZE)
                frames.append(frame)

        return frames


    def animate(self):
        self.frame += self.anim_speed
        if self.frame >= len(self.current_frames):
            self.frame = 0
        return self.current_frames[int(self.frame)]


    def set_frames(self, new_frames):
        if self.current_frames != new_frames:
            self.current_frames = new_frames
            self.frame = 0  

    def calculate_path(self, target_x, target_y, blocked):
        
        now = pygame.time.get_ticks()

        if now - self.path_timer < 150:
            return
        
        start = (
            int(self.x // self.tile_size),
            int(self.y // self.tile_size)
        )

        goal = (
            int(target_x // self.tile_size),
            int(target_y // self.tile_size)
        )

        grid_path = find_path(start, goal, blocked)

        new_path = [
            (
                gx * self.tile_size + self.tile_size // 2,
                gy * self.tile_size + self.tile_size // 2
            )
            for gx, gy in grid_path
        ]

        if new_path != self.path:
            self.path = new_path
            self.path_index = 0

        self.path_timer = now

    # Return the next waypoint on the path
    def get_next_path_target(self, fallback):

        while self.path and self.path_index < len(self.path):
            target = self.path[self.path_index]

            distance = (
                (target[0]-self.x)**2 +
                (target[1]-self.y)**2
            ) ** 0.5

            if distance < self.stop_distance:
                self.path_index += 1
                continue

            return target
        return fallback
    
    # Check if player is visible                    
    def can_see_player(self, player_x, player_y, active_walls):

        start = (self.x, self.y)
        end = (player_x, player_y)

        steps = 20

        for i in range(steps + 1):

            t = i / steps

            check_x = start[0] + (end[0] - start[0]) * t
            check_y = start[1] + (end[1] - start[1]) * t

            point = pygame.Rect(check_x - 2, check_y - 2, 4, 4)

            for wall in active_walls:
                if point.colliderect(wall):
                    return False
                
        return True

    def update(self, player_x, player_y,blocked, walls):

        if self.defeat:
            return

        if self.state == "stunned":
            if pygame.time.get_ticks() - self.stun_timer > 10000: 
                self.state = "search"
                self.last_seen = (player_x, player_y)
                self.search_timer = pygame.time.get_ticks()
            else:
                return

        if self.state == "slipping":
            now = pygame.time.get_ticks()

            if now < self.slip_until:
               self.slip_angle = (self.slip_angle + 10) % 360
               self.image = pygame.transform.rotate(self.idle_front, self.slip_angle)
               self.x -= 2
               self.y -= 1 
               self.rect.midbottom = (self.x, self.y)

            else:
               self.image = pygame.transform.rotate(self.idle_front, 90)
            if now > self.lay_until:
                self.state = "search"
                self.last_seen = (player_x, player_y)
                self.search_timer = pygame.time.get_ticks()

            return
        
        if self.state == "slowed":
            if pygame.time.get_ticks() - self.stun_timer > 5000:
                self.speed = self.original_speed
                self.state = "chasing"
               
        distance_x = player_x - self.x
        distance_y = player_y - self.y

        distance = (distance_x**2 + distance_y**2) ** 0.5

        # Player spotted
        if (
            distance < self.detect_distance
            and self.can_see_player(player_x, player_y, walls)
        ):
            if self.state != "chasing":
                self.path = []
                self.path_index = 0
                self.path_timer = 0

            self.state = "chasing"
            self.last_seen = (player_x, player_y)

        elif self.state == "chasing":
            self.state = "search"
            self.search_timer = pygame.time.get_ticks()

        # Receptionist AI behaviour 
        # Patrol state
        if self.state == "patrol":
            patrol_x, patrol_y = self.patrol_points[self.current_patrol]

            # Calculate an A* path to the current patrol point
            self.calculate_path(
                patrol_x,
                patrol_y,
                blocked
            )

            # Follow the next waypoint on the path
            target = self.get_next_path_target(
                (patrol_x, patrol_y)
            )

        # Chase state
        elif self.state == "chasing":
            
            # Update path towards the player's current position
            self.calculate_path(
                player_x,
                player_y,
                blocked
            )

            target = self.get_next_path_target(
                (player_x, player_y)
            )

        # Search state
        elif self.state == "search":
            
            if self.last_seen is None:
                self.state = "patrol"
                return
            
            # Move to the last place where the player was seen
            self.calculate_path(
                self.last_seen[0],
                self.last_seen[1],
                blocked
            )

            target = self.get_next_path_target(
                self.last_seen
            )

        dx = target[0] - self.x
        dy = target[1] - self.y

        # Calculate smooth movement towards the current target
        length = (dx * dx + dy * dy) ** 0.5

        # Stop moving when close to the target
        if length < self.stop_distance:

            # Continue following the current path
            if self.path and self.path_index < len(self.path) - 1:
                self.path_index += 1
                return
            
            # Chase keeps recalculating the player's position
            if self.state == "chasing":
                self.path = []
                self.path_index = 0
                return

            # Patrol: move to the next patrol point
            if self.state == "patrol":
                self.current_patrol += 1

                if self.current_patrol >= len(self.patrol_points):
                    self.current_patrol = 0

                # Reset old A* path so the next patrol destination gets a brand new path
                self.path = []
                self.path_index = 0
                self.path_timer = 0

                return

            # Search: finished searching
            elif self.state == "search":

                if pygame.time.get_ticks() - self.search_timer > 3000:
                    self.state = "patrol"

                    # Forget where the player was last seen
                    self.last_seen = None

                # Reset old path so patrol starts with a fresh A* path.
                self.path = []
                self.path_index = 0
                self.path_timer = 0

                return
            
            # Idle image
            if self.direction == "back":
                self.image = self.idle_back
            else:
                self.image = self.idle_front
            return
            



        # EXACT SAME STYLE AS YOUR JANITOR (no diagonal movement)

        # Movement values used for collision checking
        move_x = 0
        move_y = 0

        # Prioritize whichever axis has stronger movement
        if abs(dx) > abs(dy):   # horizontal movement dominates
            if dx > 0:
                self.direction = "right"
                self.set_frames(self.walk_right)
            else:
                self.direction = "left"
                self.set_frames(self.walk_left)
        else:                   # vertical movement dominates
            if dy > 0:
                self.direction = "front"
                self.set_frames(self.walk_front)
            else:
                self.direction = "back"
                self.set_frames(self.walk_back)

        move_x = 0
        move_y = 0

        if length !=0:
            move_x = dx / length * self.speed
            move_y = dy / length * self.speed

        # Horizontal wall collision
        test_rect = self.rect.copy()
        test_rect.centerx += round(move_x)

        
        blocked_collision = False
        
        for wall in walls:
            if test_rect.inflate(-10, -10).colliderect(wall):
                blocked_collision = True
                break

        # Move receptionist only if path not blocked
        if not blocked_collision:
            self.x += move_x
            self.rect.midbottom = (self.x, self.y)
        else:
            self.path = []
            self.path_index = 0
            self.path_timer = 0

        # Vertical wall collision 
        test_rect = self.rect.copy()
        test_rect.y += round(move_y)

        blocked_collision = False

        for wall in walls:
            if test_rect.inflate(-10, -10).colliderect(wall):
                blocked_collision = True
                break

        # Move receptionist only if path not blocked
        if not blocked_collision:
            self.y += move_y
            self.rect.midbottom = (self.x, self.y)
        else:
            self.path = []
            self.path_index = 0
            self.path_timer = 0
                
        self.image = self.animate()

        # Detect if the janitor is stuck against a wall
        current_pos = (round(self.x), round(self.y))

        if current_pos == self.last_position:
             if pygame.time.get_ticks() - self.stuck_timer > 500:
                # Force A* to generate a new path
                self.path = []
                self.path_index = 0
                self.path_timer = 0
                self.stuck_timer = pygame.time.get_ticks()
        else:
            self.last_position = current_pos
            self.stuck_timer = pygame.time.get_ticks()     

        # Handle AI state changes

        # Chase: player escaped detection range
        if self.state == "chasing":
            distance = ((player_x - self.x) ** 2 + (player_y - self.y) ** 2) ** 0.5

            # Only give up if the player is too far away
            if distance > self.detect_distance * 2:
                self.state = "search"
                self.last_seen = (player_x, player_y)
                self.search_timer = pygame.time.get_ticks()

                self.path = []
                self.path_index = 0


        # check for trap collisions
        for trap in active_traps[:]:
            if self.state == "chasing" and self.rect.colliderect(trap["rect"]):
                self.weapon_effect("BananaPeel")
                active_traps.remove(trap)
        
        self.rect.midbottom = (self.x, self.y)
 
    def draw(self, screen, camera_x=0, camera_y=0):

        rect = self.image.get_rect(
            midbottom=(
                self.x - camera_x,
                self.y - camera_y
            )
        )
        screen.blit(self.image, rect)
        
    def weapon_effect(self, effect):
        if effect == "BananaPeel":
            self.state = "slipping"
            self.slip_until = pygame.time.get_ticks() + 2000
            self.lay_until = pygame.time.get_ticks() + 40000
            self.slip_angle = 0

            # Trigger popup message
            self.popup_message = "The receptionist is now gone for 40 seconds"
            self.popup_start_time = pygame.time.get_ticks()
            self.popup_duration = 3000  # show for 3 seconds

        elif effect == "CleaningSpray":
            self.state = "stunned" 
            self.stun_timer = pygame.time.get_ticks()
            self.original_speed = self.speed 
            self.speed = max(0.5, self.speed - 0.5)

        elif effect == "KitchenKnife":
            self.state = "defeated"
            self.defeat = True
            self.popup_message = "Receptionist Defeated!"
            self.popup_start_time = pygame.time.get_ticks()
            self.popup_duration = 3000  